### ISSUE TITLE
welcome command fails to send, wunderbot errors

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-wunderbot#162]
Not sure if the message was sent or not (probably not):

jiggytom: !welcome @Zain welcome! Please read through the DMs from wunderbot.
[11:06 PM] BOTWunderbot: command welcome failed :(
TypeError: Cannot read property 'send' of undefined
    at Object.process (/home/lbry/lbry-wunder/bot/modules/welcome.js:126:33)
    at checkMessageForCommand (/home/lbry/lbry-wunder/bot/bot.js:170:13)
    at Client.bot.on.msg (/home/lbry/lbry-wunder/bot/bot.js:195:26)
    at emitOne (events.js:121:20)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (/home/lbry/lbry-wunder/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/lbry/lbry-wunder/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/home/lbry/lbry-wunder/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/lbry/lbry-wunder/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/lbry/lbry-wunder/node_modules/ws/lib/event-target.js:120:16)

**Comment by Coolguy3289** [comment]
This may have something to do with the user being set to "Show as Offline" or "Invisible", that causes issues with most bots on Discords. Or they are ignoring DMs from their servers.

**Comment by filipnyquist** [comment]
This was fixed in #181
