### ISSUE TITLE
Content bot causes crashes

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-wunderbot#95]
A bug in the code is causing crashes in the bot. 
Looking into it now
```
TypeError: Cannot read property 'send' of undefined
    at /home/lbry/lbry-wunder/bot/modules/claimbot.js:35:41
    at connectCallback (/home/lbry/lbry-wunder/node_modules/mongodb/lib/mongo_client.js:515:5)
    at /home/lbry/lbry-wunder/node_modules/mongodb/lib/mongo_client.js:430:11
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by nikooo777** [comment]
fixed in my latest version. it's all about channel IDs
